"""GDScript and Godot project file templates.

Templates provide the structural skeleton (project.godot, main.tscn).
Scripts are generated by the LLM using the full GameDesign context;
template scripts serve only as emergency fallback.
"""

from __future__ import annotations

from pathlib import Path

from v2g.llm.analyzer import GameDesign

# ── project.godot ────────────────────────────────────────────────────────────


def project_dot_godot(title: str, w: int = 1280, h: int = 720) -> str:
    return f"""\
; Engine configuration file.
; It's best edited using the editor UI and not directly.

[application]

config/name="{title}"
run/main_scene="res://main.tscn"
config/features=PackedStringArray("4.3", "GL Compatibility")

[display]

window/size/viewport_width={w}
window/size/viewport_height={h}

[input]

move_left={{
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":65,"key_label":0,"unicode":97,"echo":false,"script":null)
, Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":4194319,"key_label":0,"unicode":0,"echo":false,"script":null)
]
}}
move_right={{
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":68,"key_label":0,"unicode":100,"echo":false,"script":null)
, Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":4194321,"key_label":0,"unicode":0,"echo":false,"script":null)
]
}}
jump={{
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":32,"key_label":0,"unicode":32,"echo":false,"script":null)
, Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":4194320,"key_label":0,"unicode":0,"echo":false,"script":null)
]
}}
interact={{
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":69,"key_label":0,"unicode":101,"echo":false,"script":null)
, Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":4194309,"key_label":0,"unicode":0,"echo":false,"script":null)
]
}}

[rendering]

renderer/rendering_method="gl_compatibility"
"""


# ── UID generator ────────────────────────────────────────────────────────────


def _uid() -> str:
    """Deterministic uid; Godot just needs uniqueness within a file."""
    _uid.counter += 1
    return f"uid://v2g{_uid.counter:04d}"


_uid.counter = 0


# ── Scene (.tscn) ────────────────────────────────────────────────────────────


def main_scene(
    design: GameDesign | None = None,
    scripts: dict[str, str] | None = None,
    assets: dict[str, Path] | None = None,
) -> str:
    """Generate main.tscn from the game design.

    Builds the scene tree:
    - Main (Node2D)
      - Player (CharacterBody2D) + CollisionShape2D + Camera2D
      - Enemy_<N> (CharacterBody2D) for each enemy character
      - Environment_<N> (StaticBody2D) for environment/obstacle objects
      - Collectible_<N> (Area2D) for collectible objects
      - Trigger_<N> (Area2D) for trigger objects
      - GameManager (Node) with game_manager.gd
      - DialogueUI (CanvasLayer) if dialogue exists
    """
    uid_main = _uid()
    uid_player_script = _uid()

    # Simple counter-based IDs for sub_resources (not UIDs)
    rect_shape_id = "RectangleShape2D_1"
    circle_shape_id = "CircleShape2D_1"

    # Script ext_resources
    ext_resources: list[str] = []
    ext_resources.append(
        f'[ext_resource type="Script" path="res://player.gd" id="1_{uid_player_script}"]'
    )
    script_id_map: dict[str, str] = {"player.gd": f"1_{uid_player_script}"}

    # Collect scripts to register as ext_resources
    if scripts:
        for fname in sorted(scripts):
            if fname == "player.gd":
                continue
            uid_s = _uid()
            idx = len(ext_resources) + 1
            eid = f"{idx}_{uid_s}"
            ext_resources.append(
                f'[ext_resource type="Script" path="res://{fname}" id="{eid}"]'
            )
            script_id_map[fname] = eid

    # Texture ext_resources (from extracted assets)
    texture_id_map: dict[str, str] = {}  # asset_key → ext_resource id
    if assets:
        for asset_key, asset_path in sorted(assets.items()):
            # asset_path is absolute; we need res:// relative path
            res_path = f"res://assets/{asset_path.name}"
            uid_t = _uid()
            idx = len(ext_resources) + 1
            eid = f"{idx}_{uid_t}"
            ext_resources.append(
                f'[ext_resource type="Texture2D" path="{res_path}" id="{eid}"]'
            )
            texture_id_map[asset_key] = eid

    # Sub-resources
    sub_resources = [
        f'[sub_resource type="RectangleShape2D" id="{rect_shape_id}"]',
        "size = Vector2(32, 48)",
        "",
        f'[sub_resource type="CircleShape2D" id="{circle_shape_id}"]',
        "radius = 16.0",
    ]

    # Count load_steps = all ext_resources (scripts + textures) + sub_resources (2 shapes) + 1
    load_steps = len(ext_resources) + 2 + 1

    # Build node tree
    nodes: list[str] = []

    # Root
    nodes.append('[node name="Main" type="Node2D"]')
    nodes.append("")

    # Background sprite (from extracted asset)
    bg_tid = texture_id_map.get("background")
    if bg_tid:
        nodes.append('[node name="Background" type="Sprite2D" parent="."]')
        nodes.append(f'texture = ExtResource("{bg_tid}")')
        nodes.append("z_index = -10")
        nodes.append("centered = false")
        nodes.append("")

    # Player
    nodes.append('[node name="Player" type="CharacterBody2D" parent="."]')
    nodes.append(f'script = ExtResource("{script_id_map["player.gd"]}")')
    nodes.append("")
    nodes.append('[node name="CollisionShape2D" type="CollisionShape2D" parent="Player"]')
    nodes.append(f'shape = SubResource("{rect_shape_id}")')
    nodes.append("")
    nodes.append('[node name="Camera2D" type="Camera2D" parent="Player"]')
    nodes.append("zoom = Vector2(1, 1)")
    nodes.append("")

    # Enemies
    enemies = [c for c in (design.characters if design else []) if c.role in ("antagonist", "boss", "minion", "enemy")]
    enemy_obj = [o for o in (design.objects if design else []) if o.role == "enemy"]
    for i, enemy in enumerate(enemies[:8]):  # cap at 8
        safe = "".join(c if c.isalnum() else "_" for c in enemy.name).strip("_")[:20]
        fname = "enemy.gd"
        eid = script_id_map.get(fname, script_id_map.get("enemy.gd", f"1_{_uid()}"))
        nodes.append(f'[node name="Enemy_{safe}" type="CharacterBody2D" parent="."]')
        nodes.append(f'script = ExtResource("{eid}")')
        nodes.append("")
        nodes.append(f'[node name="CollisionShape2D" type="CollisionShape2D" parent="Enemy_{safe}"]')
        nodes.append(f'shape = SubResource("{rect_shape_id}")')
        nodes.append("")
        # Sprite from asset if available
        char_key = f"characters/{safe.lower()}"
        char_tid = texture_id_map.get(char_key)
        if char_tid:
            nodes.append(f'[node name="Sprite2D" type="Sprite2D" parent="Enemy_{safe}"]')
            nodes.append(f'texture = ExtResource("{char_tid}")')
            nodes.append("")

    # Fallback: if no characters but objects with enemy role
    if not enemies:
        for i, obj in enumerate(enemy_obj[:8]):
            safe = "".join(c if c.isalnum() else "_" for c in obj.name).strip("_")[:20]
            fname = "enemy.gd"
            eid = script_id_map.get(fname)
            if eid:
                nodes.append(f'[node name="Enemy_{safe}" type="CharacterBody2D" parent="."]')
                nodes.append(f'script = ExtResource("{eid}")')
                nodes.append("")
                nodes.append(f'[node name="CollisionShape2D" type="CollisionShape2D" parent="Enemy_{safe}"]')
                nodes.append(f'shape = SubResource("{rect_shape_id}")')
                nodes.append("")

    # Environment objects (StaticBody2D)
    env_objects = [o for o in (design.objects if design else []) if o.role in ("environment", "obstacle")]
    for i, obj in enumerate(env_objects[:12]):  # cap at 12
        safe = "".join(c if c.isalnum() else "_" for c in obj.name).strip("_")[:20]
        nodes.append(f'[node name="Env_{safe}" type="StaticBody2D" parent="."]')
        nodes.append("")
        nodes.append(f'[node name="CollisionShape2D" type="CollisionShape2D" parent="Env_{safe}"]')
        nodes.append(f'shape = SubResource("{rect_shape_id}")')
        nodes.append("")

    # Collectibles (Area2D)
    collectibles = [o for o in (design.objects if design else []) if o.role == "collectible"]
    for i, obj in enumerate(collectibles[:16]):  # cap at 16
        safe = "".join(c if c.isalnum() else "_" for c in obj.name).strip("_")[:20]
        nodes.append(f'[node name="Collectible_{safe}" type="Area2D" parent="."]')
        nodes.append("")
        nodes.append(f'[node name="CollisionShape2D" type="CollisionShape2D" parent="Collectible_{safe}"]')
        nodes.append(f'shape = SubResource("{circle_shape_id}")')
        nodes.append("")
        # Sprite from asset if available
        obj_key = f"objects/{safe.lower()}"
        obj_tid = texture_id_map.get(obj_key)
        if obj_tid:
            nodes.append(f'[node name="Sprite2D" type="Sprite2D" parent="Collectible_{safe}"]')
            nodes.append(f'texture = ExtResource("{obj_tid}")')
            nodes.append("")

    # Triggers (Area2D)
    triggers = [o for o in (design.objects if design else []) if o.role == "trigger"]
    for i, obj in enumerate(triggers[:8]):
        safe = "".join(c if c.isalnum() else "_" for c in obj.name).strip("_")[:20]
        nodes.append(f'[node name="Trigger_{safe}" type="Area2D" parent="."]')
        nodes.append("")
        nodes.append(f'[node name="CollisionShape2D" type="CollisionShape2D" parent="Trigger_{safe}"]')
        nodes.append(f'shape = SubResource("{rect_shape_id}")')
        nodes.append("")

    # GameManager
    gm_eid = script_id_map.get("game_manager.gd")
    if gm_eid:
        nodes.append('[node name="GameManager" type="Node" parent="."]')
        nodes.append(f'script = ExtResource("{gm_eid}")')
        nodes.append("")

    # DialogueUI (CanvasLayer) — only if dialogue exists
    if design and design.dialogue_samples:
        dlg_eid = script_id_map.get("dialogue_ui.gd")
        if dlg_eid:
            nodes.append('[node name="DialogueUI" type="CanvasLayer" parent="."]')
            nodes.append("layer = 10")
            nodes.append("")
            nodes.append('[node name="DialoguePanel" type="Panel" parent="DialogueUI"]')
            nodes.append("anchors_preset = 2")
            nodes.append("anchor_left = 0.0")
            nodes.append("anchor_top = 1.0")
            nodes.append("anchor_right = 1.0")
            nodes.append("anchor_bottom = 1.0")
            nodes.append("offset_left = 20.0")
            nodes.append("offset_top = -150.0")
            nodes.append("offset_right = -20.0")
            nodes.append("offset_bottom = -20.0")
            nodes.append("")
            nodes.append('[node name="DialogueLabel" type="RichTextLabel" parent="DialogueUI/DialoguePanel"]')
            nodes.append("layout_mode = 2")
            nodes.append("anchors_preset = 15")
            nodes.append("anchor_right = 1.0")
            nodes.append("anchor_bottom = 1.0")
            nodes.append("offset_left = 10.0")
            nodes.append("offset_top = 10.0")
            nodes.append("offset_right = -10.0")
            nodes.append("offset_bottom = -10.0")
            nodes.append("bbcode_enabled = true")
            nodes.append("")
            nodes.append('[node name="NameLabel" type="Label" parent="DialogueUI/DialoguePanel"]')
            nodes.append("layout_mode = 0")
            nodes.append("offset_left = 10.0")
            nodes.append("offset_top = -30.0")
            nodes.append("offset_right = 300.0")
            nodes.append("offset_bottom = 0.0")
            nodes.append("")

    # Assemble
    ext_block = "\n".join(ext_resources)
    sub_block = "\n".join(sub_resources)
    node_block = "\n".join(nodes).rstrip()

    return f"""\
[gd_scene load_steps={load_steps} format=3 {uid_main}]

{ext_block}

{sub_block}

{node_block}
"""


# ── Fallback GDScript generators ─────────────────────────────────────────────
# These are used ONLY if the LLM script generation fails.


def player_script(design: GameDesign) -> str:
    """Fallback: basic CharacterBody2D player controller."""
    speed = "300.0"
    jump_vel = "-400.0"
    if "endless-runner" in design.genre.lower():
        speed = "400.0"
        jump_vel = "-500.0"
    if "rpg" in design.genre.lower() or "adventure" in design.genre.lower():
        speed = "200.0"
        jump_vel = "-350.0"

    return f"""\
extends CharacterBody2D

const SPEED = {speed}
const JUMP_VELOCITY = {jump_vel}

var gravity: float = ProjectSettings.get_setting("physics/2d/default_gravity")

@onready var sprite := $Sprite2D if has_node("Sprite2D") else null

func _physics_process(delta: float) -> void:
    if not is_on_floor():
        velocity.y += gravity * delta

    if Input.is_action_just_pressed("jump") and is_on_floor():
        velocity.y = JUMP_VELOCITY

    var direction := Input.get_axis("move_left", "move_right")
    if direction:
        velocity.x = direction * SPEED
    else:
        velocity.x = move_toward(velocity.x, 0, SPEED)

    if sprite and direction != 0.0:
        sprite.flip_h = direction < 0.0

    move_and_slide()
"""


def enemy_script() -> str:
    """Fallback: basic patrol enemy."""
    return """\
extends CharacterBody2D

const SPEED = 150.0
var direction := -1.0

var gravity: float = ProjectSettings.get_setting("physics/2d/default_gravity")

func _physics_process(delta: float) -> void:
    if not is_on_floor():
        velocity.y += gravity * delta

    velocity.x = direction * SPEED
    move_and_slide()

    if is_on_wall():
        direction *= -1.0
"""


def game_manager_script(design: GameDesign) -> str:
    """Fallback: basic score + goals game manager."""
    goals = ", ".join(f'"{g}"' for scene in design.scenes for g in scene.goals)
    return f"""\
extends Node

signal score_changed(new_score: int)
signal game_over

var score: int = 0
var goals: Array = [{goals}]

func add_score(amount: int = 1) -> void:
    score += amount
    score_changed.emit(score)

func end_game() -> void:
    game_over.emit()
    print("Game Over! Final score: ", score)
"""


# ── LLM script generation prompt ─────────────────────────────────────────────

LLM_SCRIPT_SYSTEM = """\
You are a Godot 4.x GDScript expert and game developer. You will receive a
comprehensive game design document as JSON. Your task is to generate ALL the
GDScript files needed to make this game playable.

The game was generated from a video — your scripts must faithfully recreate the
characters, environments, narrative, and gameplay shown in the source material.

OUTPUT FORMAT:
Return a JSON object mapping filenames to their complete GDScript source code.

{
  "player.gd": "extends CharacterBody2D\\n...",
  "enemy.gd": "extends CharacterBody2D\\n...",
  "game_manager.gd": "extends Node\\n...",
  "dialogue_ui.gd": "extends CanvasLayer\\n...",
  "any_other_file.gd": "extends Node\\n..."
}

REQUIRED FILES (you MUST generate these):
- player.gd — Player controller. Movement, abilities, interactions. Match the
  character's described behavior and abilities. Use CharacterBody2D.
- game_manager.gd — Game state: score, goals, scene transitions, win/lose conditions.
  Emit signals for UI updates. Use the "scenes" and "goals" from the design.

RECOMMENDED FILES (generate if the design calls for them):
- enemy.gd — Enemy AI for each enemy type. Patrol, chase, attack patterns matching
  the design's character behavior descriptions.
- dialogue_ui.gd — Dialogue system if the design has dialogue_samples. Show speaker
  name, line text, advance on input. Use CanvasLayer + Panel + RichTextLabel.
- camera_controller.gd — Camera behavior if needed (follow, zoom, shake, cutscene).
- Any character-specific scripts for NPCs, companions, bosses.
- Any mechanic-specific scripts (inventory, combat, puzzle, stealth).
- Any UI scripts (health bar, minimap, menu, HUD).

GODOT 4.x RULES:
- Use `@onready`, `@export`, typed variables (`var x: int = 0`)
- Signals: `signal name(param: type)` and `name.emit(value)`
- No `yield` — use `await` for coroutines
- Input: `Input.is_action_just_pressed("action_name")`
- Movement: `CharacterBody2D.move_and_slide()` after setting `velocity`
- Access nodes: `$NodeName` or `get_node("path")`
- Groups: `get_tree().get_nodes_in_group("group_name")`
- Scene change: `get_tree().change_scene_to_file("res://scene.tscn")`
- Autoload: reference by name (e.g., `GameManager.add_score(1)`)

DESIGN FIDELITY:
- Character behavior scripts MUST match the design's "behavior" fields
- Enemy AI MUST match described patrol/attack/react patterns
- Dialogue UI MUST be able to display the dialogue_samples from the design
- Game manager MUST track the goals defined in each scene
- Physics values (speed, jump, gravity) MUST match the "physics" field
- Use the "progression" field to implement difficulty scaling
- Characters with multiple "personas" (different outfits/costumes) should have
  costume-change logic: e.g. a function `set_persona(index)` that swaps sprite
  textures and adjusts stats if the persona has different abilities

CODE QUALITY:
- Self-contained scripts — no external dependencies beyond Godot built-ins
- Include comments explaining key logic
- Handle edge cases (null nodes, missing groups, first-frame guards)
- Use `_ready()` for initialization, `_process()` or `_physics_process()` for updates
"""
